<?php
/*
 * Copyright (c) 2012 KUBO Atsuhiro <kubo@iteman.jp>,
 * All rights reserved.
 *
 * This file is part of Piece_Flow.
 *
 * This program and the accompanying materials are made available under
 * the terms of the BSD 2-Clause License which accompanies this
 * distribution, and is available at http://opensource.org/licenses/BSD-2-Clause
 */

namespace Piece\Flow\Pageflow;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * @since Class available since Release 0.1.0
 */
class Definition17Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $treeBuilder->root('definition17')
            ->children()
                ->scalarNode('firstState')->isRequired()->cannotBeEmpty()->end()
                ->arrayNode('viewState')
                    ->isRequired()
                    ->requiresAtLeastOneElement()
                    ->prototype('array')
                        ->children()
                            ->scalarNode('name')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('view')->isRequired()->cannotBeEmpty()->end()
                            ->arrayNode('transition')
                                ->prototype('array')
                                    ->children()
                                        ->scalarNode('event')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('nextState')->isRequired()->cannotBeEmpty()->end()
                                        ->arrayNode('action')
                                            ->children()
                                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('guard')
                                            ->children()
                                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('entry')
                                ->children()
                                    ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                    ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('exit')
                                ->children()
                                    ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                    ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('activity')
                                ->children()
                                    ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                    ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('actionState')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('name')->isRequired()->cannotBeEmpty()->end()
                            ->arrayNode('transition')
                                ->isRequired()
                                ->requiresAtLeastOneElement()
                                ->prototype('array')
                                    ->children()
                                        ->scalarNode('event')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('nextState')->isRequired()->cannotBeEmpty()->end()
                                        ->arrayNode('action')
                                            ->children()
                                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('guard')
                                            ->children()
                                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('entry')
                                ->children()
                                    ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                    ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('exit')
                                ->children()
                                    ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                    ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('activity')
                                ->children()
                                    ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                    ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('lastState')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('name')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('view')->isRequired()->cannotBeEmpty()->end()
                        ->arrayNode('entry')
                            ->children()
                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                            ->end()
                        ->end()
                        ->arrayNode('exit')
                            ->children()
                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                            ->end()
                        ->end()
                        ->arrayNode('activity')
                            ->children()
                                ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                                ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('initial')
                    ->children()
                        ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                        ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                    ->end()
                ->end()
                ->arrayNode('final')
                    ->children()
                        ->scalarNode('class')->defaultNull()->cannotBeEmpty()->end()
                        ->scalarNode('method')->isRequired()->cannotBeEmpty()->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
